### PR TITLE
Prepare for CRAN re-submission

### PR DESCRIPTION
**Pull request by manchen07**
I've run the win-builder checks (devel, release, oldrelease) and the rhub checks on various platforms. The results look good. 

I ran the `devtools::check(env_vars = c(`_R_CHECK_DEPENDS_ONLY_` = TRUE))` and fixed the unit tests and removed one example.

The revdep check shows that scdhlm 0.5.2 is broken. Because we imported lmeInfo to scdhlm and the removal of returnModel in `g_mlm()` seems causing the problem for some example and test in scdhlm package. See revdep/problems.md for more detail. 

Could you please let me know what's the next step? Thanks!

### CODE REVIEW

**Comment by manchen07** [comment]
And I'm re-installing R now...Have been using 4.1.0 for too long...

**Comment by jepusto** [comment]
> And I'm re-installing R now...Have been using 4.1.0 for too long...

Ha. R 4.2.1 is scheduled for release next week (6/23).

**Comment by manchen07** [comment]
> > And I'm re-installing R now...Have been using 4.1.0 for too long...
> 
> Ha. R 4.2.1 is scheduled for release next week (6/23).

Yes...I just saw that...I guess I'll stick to 4.1.0 for another week.

**Review by jepusto — APPROVED** [review]

**Comment by jepusto** [comment]
For the reverse-dependency on scdhlm, I can think of two possible options:
1. Add a `...` argument to `g_mlm()`, but let it have no effect on the output. Then, after we've posted a new version of scdhlm to CRAN (and corrected the unit tests/examples that specify `returnModel`), we can take the `...` out for the next version of `lmeInfo`.
2. Correct the unit tests/examples in scdhlm, post the new version to CRAN, and only then post the new version of lmeInfo.

**Comment by jepusto** [comment]
I pushed a commit to avoid using {dplyr} and {tidyr} in the unit tests, so that we can remove them from SUGGESTS.

**Comment by jepusto** [comment]
> For the reverse-dependency on scdhlm, I can think of two possible options:
> 
> 1. Add a `...` argument to `g_mlm()`, but let it have no effect on the output. Then, after we've posted a new version of scdhlm to CRAN (and corrected the unit tests/examples that specify `returnModel`), we can take the `...` out for the next version of `lmeInfo`.
> 2. Correct the unit tests/examples in scdhlm, post the new version to CRAN, and only then post the new version of lmeInfo.

Which direction do you think we should go? (Or perhaps some other strategy?)

**Comment by manchen07** [comment]
> > For the reverse-dependency on scdhlm, I can think of two possible options:
> > 
> > 1. Add a `...` argument to `g_mlm()`, but let it have no effect on the output. Then, after we've posted a new version of scdhlm to CRAN (and corrected the unit tests/examples that specify `returnModel`), we can take the `...` out for the next version of `lmeInfo`.
> > 2. Correct the unit tests/examples in scdhlm, post the new version to CRAN, and only then post the new version of lmeInfo.
> 
> Which direction do you think we should go? (Or perhaps some other strategy?)

We would submit a new version of scdhlm to CRAN within one month after adding the 3-level models, right? Then maybe we could go with the second direction. But I'm okay with the first direction as well. The package is ready for submission (after adding ...). I'm more than happy to submit it to CRAN this week. Please let me know what you decide.

**Comment by jepusto** [comment]
Let’s go with the … approach then. It would be nice to get lmeInfo up on CRAN so that we can leave it alone for a while.

**Comment by manchen07** [comment]
Just added it. I'm re-running all checks.

**Comment by manchen07** [comment]
I've pushed the commits adding ... argument and revdepcheck results to cran-comments. Unfortunately, the rhub checks are not running right now. I can rerun them tomorrow.

**Pull request merged**
